name: Release New Tags

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Any pushed tag

jobs:
  build:
    name: Create Release

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - uses: pCYSl5EDgo/cat@master
        id: loadChangelog
        with:
          path: CHANGELOG-current.md

      - name: Create Release
        id: createRelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ATEOAT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.loadChangelog.outputs.text }}
          draft: false
          prerelease: false

      - name: Output Release URL File
        run: echo "${{ steps.createRelease.outputs.upload_url }}" > release_url.txt

      - name: Save Release URL File for Publish
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

      - name: Build Blog Post for Version Update
        run: npm run util:blogpost:generate

      - name: Read blog_post.txt file
        id: getBlogPost
        run: echo "filename=$(cat blog-post.txt)" >> $GITHUB_OUTPUT

      - name: Publish Version Update Blog Post
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TO_REPO_TOKEN }}
        with:
          source_file: '${{ steps.getBlogPost.outputs.filename }}'
          destination_repo: 'After-the-End-of-All-Things/blog'
          destination_folder: '_posts'
          user_email: 'kyle@seiyria.com'
          user_name: 'seiyria'
          commit_message: 'Add version notes'
          destination_branch: master
