name: Tag New Release

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: What kind of version?
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  tag:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - run: npm run lint

      - run: npm run build

      - name: Run Versioning
        run: npm run bump:${{ github.event.inputs.type }} --ignore-scripts

      - name: Generate Changelogs
        run: npm run util:changelog:generate && npm run util:changelog:generate:current

      - name: Commit Changelogs
        run: npm run util:changelog:commit && npm run util:version:reversion

      - name: Push Changelogs
        run: git push && git push --tags
